services:
  alloy:
    image: grafana/alloy:v1.12.0
    container_name: alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/machine-id:/etc/machine-id:ro
      - /:/host:ro,rslave
      - ~/repository/monitoring/alloy/config_manager.alloy:/etc/alloy/config.alloy
      - ~/data/alloy:/var/lib/alloy/data
    env_file:
      - ~/config/common/base.env
      - ~/config/alloy/app.env
    ports:
      - '12345:12345'
    networks:
      - common_network
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    restart: always

networks:
  common_network:
    external: true
