services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.1
    container_name: pocket-id
    volumes:
      - ~/data/pocket-id:/app/data
    env_file:
      - ~/config/common/base.env
      - ~/config/pocket-id/app.env
    ports:
      - '1411:1411'
    networks:
      - common_network
    restart: always
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

networks:
  common_network:
    external: true
