services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.13.0
    container_name: oauth2-proxy
    volumes:
      - ~/config/oauth2-proxy/oauth2-proxy.cfg:/oauth2-proxy.cfg
    networks:
      - common_network
    command: --config /oauth2-proxy.cfg
    restart: always
    user: "1000:1000"

networks:
  common_network:
    external: true
