services:
  smartctl-exporter:
    image: ghcr.io/joryirving/smartctl_exporter:v0.14.0
    container_name: smartctl-exporter
    env_file:
      - ~/config/common/base.env
    ports:
      - '9663:9663'
    networks:
      - common_network
    restart: always
    user: root
    privileged: true

networks:
  common_network:
    external: true
