services:
  mailpit:
    image: axllent/mailpit:v1.28
    container_name: mailpit
    env_file:
      - ~/config/common/base.env
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - common_network
    restart: always

networks:
  common_network:
    external: true
