services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:v1.47.0
    container_name: homarr
    volumes:
      - ~/data/homarr:/appdata
    env_file:
      - ~/config/common/base.env
      - ~/config/homarr/app.env
    networks:
      - common_network
    restart: always

networks:
  common_network:
    external: true
