services:
  mosquitto-exporter:
    image: jryberg/mosquitto-exporter:v0.7.7
    container_name: mosquitto-exporter
    env_file:
      - ~/config/common/base.env
      - ~/config/mosquitto-exporter/app.env
    ports:
      - '9234:9234'
    networks:
      - common_network
    restart: always

networks:
  common_network:
    external: true
