services:
  nginx:
    image: nginx:1.29.4
    container_name: nginx
    volumes:
      - ~/repository/nana4-net/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/repository/nana4-net/nginx/conf.d:/etc/nginx/conf.d:ro
      - ~/repository/nana4-net/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ~/repository/nana4-net/nginx/html:/usr/share/nginx/html:ro
    env_file:
      - ~/config/common/base.env
      - ~/config/nginx/app.env
    networks:
      - common_network
    restart: always

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    container_name: nginx-prometheus-exporter
    depends_on:
      - nginx
    networks:
      - common_network
    command:
      - "--nginx.scrape-uri=http://nginx:9900/stub_status"
    restart: always

networks:
  common_network:
    external: true
