services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.1
    container_name: cloudflared
    env_file:
      - ~/config/cloudflared/app.env
    networks:
      - common_network
    command: tunnel --no-autoupdate run
    restart: always

networks:
  common_network:
    external: true
