services:
  portainer:
    image: portainer/portainer-ce:2.37.0
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/data/portainer:/data
    env_file:
      - ~/config/common/base.env
    networks:
      - common_network
    restart: always

networks:
  common_network:
    external: true
